# dont add these items to the output
IGNORED = [
    "",
    "head",
    "body",
    "arms",
    "legs",
    "travel-hairstyle",
    "millicents-robe",
    "millicents-gloves",
    "millicents-boots",
    "millicents-tunic",
    "millicents-robe",
    "braves-cord-circlet",
    "braves-battlewear",
    "braves-battlewear-altered",
    "braves-bracer",
    "braves-legwraps",
    "braves-leather-helm",
    "ragged-hat",
    "ragged-hat-altered",
    "ragged-armor",
    "ragged-armor-altered",
    "ragged-gloves",
    "ragged-loincloth",
    "deathbed-smalls",
    # these items are wrong in the param files
    "ash-of-war-scarab",
    "fias-robe",
    "fias-robe-altered",
    "deathbed-dress",
    "rotten-duelist-greaves",
]

# these items are either missing or wrong in the param files
MISSING = {
    "helmets": {
        "ash-of-war-scarab": {
            "id": "ash-of-war-scarab",
            "name": "Ash-of-War Scarab",
            "defenses": {"physical": -5.82, "strike": -5.6, "slash": -5.82, "pierce": -5.82, "magic": -4.94, "fire": -4.94, "lightning": -4.94, "holy": -5.05},
            "resistances": {"poison": 42, "scarletRot": 42, "hemorrhage": 22, "frostbite": 22, "sleep": 27, "madness": 27, "deathBlight": 26},
            "poise": 6,
            "weight": 5.1,
        },
    },
    "chestpieces": {
        "fias-robe": {
            "id": "fias-robe",
            "name": "Fia's Robe",
            "defenses": {"physical": 5.3, "strike": 6.1, "slash": 5.3, "pierce": 5.3, "magic": 12.6, "fire": 12.4, "lightning": 12.6, "holy": 13},
            "resistances": {"poison": 46, "scarletRot": 46, "hemorrhage": 21, "frostbite": 21, "sleep": 76, "madness": 76, "deathBlight": 108},
            "poise": 2,
            "weight": 5.1,
        },
        "fias-robe-altered": {
            "id": "fias-robe-altered",
            "name": "Fia's Robe (Altered)",
            "defenses": {"physical": 2.7, "strike": 4.2, "slash": 2.7, "pierce": 2.7, "magic": 11.9, "fire": 11.4, "lightning": 11.9, "holy": 12.6},
            "resistances": {"poison": 34, "scarletRot": 34, "hemorrhage": 10, "frostbite": 10, "sleep": 57, "madness": 57, "deathBlight": 93},
            "poise": 0,
            "weight": 3.2,
        },
        "deathbed-dress": {
            "id": "deathbed-dress",
            "name": "Deathbed Dress",
            "defenses": {"physical": 0.6, "strike": 2.7, "slash": 0.6, "pierce": 0.6, "magic": 11.9, "fire": 11.4, "lightning": 11.9, "holy": 12.4},
            "resistances": {"poison": 38, "scarletRot": 38, "hemorrhage": 11, "frostbite": 11, "sleep": 63, "madness": 63, "deathBlight": 107},
            "poise": 1,
            "weight": 3.2,
        },
    },
    "gauntlets": {
    },
    "leggings": {
        "rotten-duelist-greaves": {
            "id": "rotten-duelist-greaves",
            "name": "Rotten Duelist Greaves",
            "defenses": {"physical": 7.4, "strike": 6.2, "slash": 7.7, "pierce": 7.1, "magic": 6.2, "fire": 6.5, "lightning": 5.8, "holy": 6.2},
            "resistances": {"poison": 35, "scarletRot": 35, "hemorrhage": 35, "frostbite": 35, "sleep": 15, "madness": 15, "deathBlight": 15},
            "poise": 10,
            "weight": 7.3,
        },
    },
}

# until i find where this is located in the param files, this is the workaround
STAT_BUFFS = {
    "albinauric-mask": {"VIG": 0, "MND": 0, "END": 0, "STR": 0, "DEX": 0, "INT": 0, "FTH": 0, "ARC": 1},
    "circlet-of-light": {"VIG": 0, "MND": 0, "END": 0, "STR": 0, "DEX": 0, "INT": 1, "FTH": 0, "ARC": 1},
    "commoners-garb": {"VIG": 0, "MND": 0, "END": 0, "STR": 0, "DEX": 0, "INT": 0, "FTH": 1, "ARC": 0},
    "consorts-mask": {"VIG": 0, "MND": 0, "END": 0, "STR": 0, "DEX": 1, "INT": 0, "FTH": 0, "ARC": 0},
    "crimson-hood": {"VIG": 1, "MND": 0,  "END": 0, "STR": 0, "DEX": 0, "INT": 0, "FTH": 0, "ARC": 0},
    "divine-beast-head": {"VIG": 0, "MND": 0, "END": 0, "STR": 0, "DEX": 4, "INT": 0, "FTH": 0, "ARC": 0},
    "greathood": {"VIG": 0, "MND": 0, "END": 0, "STR": 0, "DEX": 0, "INT": 2, "FTH": 2, "ARC": 0},
    "haima-glintstone-crown": {"VIG": 0, "MND": 0, "END": 0, "STR": 2, "DEX": 0, "INT": 2, "FTH": 0, "ARC": 0},
    "haligtree-helm": {"VIG": 0, "MND": 0, "END": 0, "STR": 0, "DEX": 0, "INT": 0, "FTH": 1, "ARC": 0},
    "haligtree-knight-helm": {"VIG": 0, "MND": 0, "END": 0, "STR": 0,"DEX":  0, "INT": 0, "FTH": 2, "ARC": 0},
    "hierodas-glintstone-crown": {"VIG": 0, "MND": 0, "END": 2, "STR": 0, "DEX": 0, "INT": 2, "FTH": 0, "ARC": 0},
    "high-priest-hat": {"VIG": 0, "MND": 0, "END": 0, "STR": 0, "DEX": 0, "INT": 1, "FTH": 0, "ARC": 1},
    "imp-head-cat": {"VIG": 0, "MND": 0, "END": 0, "STR": 0, "DEX": 0, "INT": 2, "FTH": 0, "ARC": 0},
    "imp-head-corpse": {"VIG": 0, "MND": 0, "END": 0, "STR": 0, "DEX": 0, "INT": 0, "FTH": 2, "ARC": 0},
    "imp-head-elder": {"VIG": 0, "MND": 0, "END": 0, "STR": 0, "DEX": 0, "INT": 0, "FTH": 0, "ARC": 2},
    "imp-head-fanged": {"VIG": 0, "MND": 0, "END": 0, "STR": 2, "DEX": 0, "INT": 0, "FTH": 0, "ARC": 0},
    "imp-head-long-tongued": {"VIG": 0, "MND": 0, "END": 0, "STR": 0, "DEX": 2, "INT": 0, "FTH": 0, "ARC": 0},
    "imp-head-wolf": {"VIG": 0, "MND": 0, "END": 2, "STR": 0, "DEX": 0, "INT": 0, "FTH": 0, "ARC": 0},
    "karolos-glinstone-crown": {"VIG": 0, "MND": 0, "END": 0, "STR": 0, "DEX": 0, "INT": 3, "FTH": 0, "ARC": 0},
    "lamenters-mask": {"VIG": 0, "MND": 0, "END": 0, "STR": 0, "DEX": 0, "INT": 0, "FTH": 0, "ARC": 8},
    "lazuli-glintstone-crown": {"VIG": 0, "MND": 0, "END": 0, "STR": 0, "DEX": 3, "INT": 3, "FTH": 0, "ARC": 0},
    "marais-mask": {"VIG": 0, "MND": 0, "END": 0, "STR": 0, "DEX": 0, "INT": 0, "FTH": 0, "ARC": 1},
    "mask-of-confidence": {"VIG": 0, "MND": 0, "END": 0, "STR": 0, "DEX": 0, "INT": 0, "FTH": 0, "ARC": 3},
    "navy-hood": {"VIG": 0, "MND": 1, "END": 0, "STR": 0, "DEX": 0, "INT": 0, "FTH": 0, "ARC": 0},
    "okina-mask": {"VIG": 0, "MND": 0, "END": 0, "STR": 0, "DEX": 3, "INT": 0, "FTH": 0, "ARC": 0},
    "olivinus-glintstone-crown": {"VIG": 0, "MND": 0, "END": 0, "STR": 0, "DEX": 0, "INT": 3, "FTH": 0, "ARC": 0},
    "omensmirk-mask": {"VIG": 0, "MND": 0, "END": 0, "STR": 2, "DEX": 0, "INT": 0, "FTH": 0, "ARC": 0},
    "preceptors-big-hat": {"VIG": 0, "MND": 3, "END": 0, "STR": 0, "DEX": 0, "INT": 0, "FTH": 0, "ARC": 0},
    "queens-crescent-crown": {"VIG": 0, "MND": 0, "END": 0, "STR": 0, "DEX": 0, "INT": 3, "FTH": 0, "ARC": 0},
    "rulers-mask": {"VIG": 0, "MND": 0, "END": 0, "STR": 0, "DEX": 0, "INT": 0, "FTH": 1, "ARC": 0},
    "sacred-crown-helm": {"VIG": 0, "MND": 0, "END": 0, "STR": 0, "DEX": 0, "INT": 0, "FTH": 1, "ARC": 0},
    "salzas-hood": {"VIG": 0, "MND": 0, "END": 0, "STR": 0, "DEX": 0, "INT": 2, "FTH": 0, "ARC": 0},
    "silver-tear-mask": {"VIG": 0, "MND": 0, "END": 0, "STR": 0, "DEX": 0, "INT": 0, "FTH": 0, "ARC": 8},
    "thiolliers-garb": {"VIG": 0, "MND": 0, "END": 0, "STR": 0, "DEX": 0, "INT": 0, "FTH": 0, "ARC": 2},
    "thiolliers-mask": {"VIG": 0, "MND": 0, "END": 0, "STR": 0, "DEX": 0, "INT": 0, "FTH": 0, "ARC": 3},
    "twinsage-glintstone-crown": {"VIG": 0, "MND": 0, "END": 0, "STR": 0, "DEX": 0, "INT": 6, "FTH": 0, "ARC": 0},
    "witchs-glintstone-crown": {"VIG": 0, "MND": 0, "END": 0, "STR": 0, "DEX": 0, "INT": 3, "FTH": 0, "ARC": 3},
}

IGNORED_WEAPON_INFUSIONS = [
    "heavy-crossbow",
    "bloody-helice",
    "mohgwyns-sacred-spear",
    "sacred-relic-sword",
    "treespear",
    "serpentbone-blade",
    'bloodfiends-sacred-spear',
    'lightning-perfume-bottle',
    'deadly-poison-perfume-bottle',
    'trolls-hammer'
    # "fire-knights-greatsword",
    # "fire-knights-shortsword"
]
